-- ===========================================================================
-- Kasama — Supabase schema + seed data
-- ---------------------------------------------------------------------------
-- Run this in the Supabase Dashboard → SQL Editor → New query → Run.
-- It creates the two tables the frontend reads from and fills them with
-- starter content (real Singapore helplines + accurate FDW rights info).
--
-- Safe to re-run: it clears and re-inserts the seed rows each time.
-- ===========================================================================

-- ---------- contacts: the Help & Helplines directory -----------------------
create table if not exists public.contacts (
  id           bigint generated by default as identity primary key,
  name         text not null,
  category     text not null,            -- emergency | work | embassies | wellbeing
  phone        text not null,            -- shown as-is; the app strips spaces for tel:
  description  text,
  place_id     text,                     -- optional link to a curated place (e.g. 'mustafa')
  sort_order   int  not null default 0,
  created_at   timestamptz not null default now()
);

-- ---------- rights_pages: the Know Your Rights library ---------------------
create table if not exists public.rights_pages (
  id          bigint generated by default as identity primary key,
  slug        text not null unique,      -- used in the URL: /rights/:slug
  category    text not null,             -- e.g. 'Pay', 'Rest & time off'
  title       text not null,
  summary     text not null,             -- one-line preview shown on the list
  body        text not null,             -- plain text; '-' or '•' start a bullet line
  updated_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Row Level Security: the helplines and rights content are public reference
-- info, so anyone (anon + authenticated) can read them. Nothing is writable
-- from the client — content is managed here, in SQL.
-- ---------------------------------------------------------------------------
alter table public.contacts     enable row level security;
alter table public.rights_pages enable row level security;

drop policy if exists "contacts are public"     on public.contacts;
drop policy if exists "rights are public"       on public.rights_pages;
create policy "contacts are public" on public.contacts
  for select using (true);
create policy "rights are public" on public.rights_pages
  for select using (true);

-- ===========================================================================
-- Seed: helplines
-- Numbers verified against public Singapore sources (MOM, SCDF, TADM, SOS,
-- Embassy of the Republic of the Philippines). Worth re-checking periodically.
-- ===========================================================================
delete from public.contacts;
insert into public.contacts (name, category, phone, description, place_id, sort_order) values
  ('Police (Emergency)',          'emergency', '999',              'For crimes, danger to life, or anything happening right now.', null, 1),
  ('Ambulance & Fire (SCDF)',     'emergency', '995',              'Medical emergencies, fires and rescue.', null, 2),
  ('Police Non-Emergency',        'emergency', '1800 255 0000',    'Report non-urgent matters to the police.', null, 3),
  ('Ministry of Manpower (MOM)',  'work',      '6438 5122',        'Work pass, salary and employment-condition questions.', null, 1),
  ('TADM — Salary & Claims',      'work',      '1800 336 4056',    'Free help with salary and statutory claims (Tripartite Alliance).', null, 2),
  ('Philippines Embassy',         'embassies', '6737 3977',        'Consular help for Filipino citizens in Singapore.', 'philippines-embassy', 1),
  ('Samaritans of Singapore',     'wellbeing', '1767',             'Confidential emotional support, 24 hours a day.', null, 1);

-- ===========================================================================
-- Seed: rights library
-- Content reflects Ministry of Manpower rules for foreign domestic workers
-- (FDWs). Kept short and plain on purpose — this is a starting point, not
-- legal advice.
-- ===========================================================================
delete from public.rights_pages;
insert into public.rights_pages (slug, category, title, summary, body) values
(
  'rest-days',
  'Rest & time off',
  'Rest days',
  'You are entitled to at least one rest day every week.',
  'You must get at least one rest day every week. A rest day means a full day off — midnight to midnight — with no work.

A few things worth knowing:
- Your rest day cannot simply be replaced with extra pay. It can only happen for special reasons and only if you agree in writing.
- If you do work on your rest day, your employer must compensate you.
- Your rest days are set out in your contract and protected by law.

If you are being denied rest days, keep your own record of your working hours and contact the Ministry of Manpower.'
),
(
  'salary-and-deductions',
  'Pay',
  'Salary & deductions',
  'Your salary must be paid in full and on time.',
  'Your employer must pay your salary in full at least once a month, within 7 days after the end of each salary period.

What employers cannot do:
- Deduct money for food, lodging or other "expenses" beyond what the law and your contract allow.
- Withhold your salary as a punishment or to recover a loan.
- Pay you less than the amount in your contract.

Keep your own record of every payment — date and amount. The app''s "My pay" page is built for exactly this. If something is off, you can file a salary claim with TADM within the time limit.'
),
(
  'employment-contract',
  'Contract',
  'Your employment contract',
  'The Standard Employment Contract sets out your agreed terms.',
  'Foreign domestic workers in Singapore work under a Standard Employment Contract (SEC). It records the terms both you and your employer agreed to.

Your contract should clearly state:
- Your monthly salary.
- Your rest day arrangement.
- Your duties and working hours.
- Your medical and other benefits.

Both you and your employer should have a signed copy. If you are not sure what is in yours, ask your employer or your employment agency to go through it with you.'
),
(
  'medical-care',
  'Health & safety',
  'Medical care',
  'Your employer must cover the cost of your medical treatment.',
  'While you are employed, your employer is responsible for your medical care.

The important parts:
- Your employer must bear the full cost of your medical treatment.
- This includes outpatient care and, if needed, hospital stays (up to the limits set by law).
- You should never be asked to pay for the treatment of a work injury or illness.

If you feel unwell, tell your employer early and get treated. In a medical emergency, call 995.'
);
