-- Kasama — Supabase schema + seed data
-- ---------------------------------------------------------------------------
-- It creates the two tables the frontend reads from and fills them with
-- starter content (real Singapore helplines + accurate FDW rights info).
--
-- The same content also ships in the app as a static fallback
-- (src/data/contacts.js, src/data/rights.js) so the pages are never empty, even with no backend
--
-- Safe to re-run: it clears and re-inserts the seed rows each time.

-- ---------- contacts: the Help & Helplines directory -----------------------
create table if not exists public.contacts (
  id           bigint generated by default as identity primary key,
  name         text not null,
  category     text not null,            -- emergency | work | embassies | wellbeing
  phone        text not null,            -- shown as-is; the app strips spaces for tel:
  description  text,
  place_id     text,                     -- optional link to a curated place (e.g. 'mustafa')
  sort_order   int  not null default 0,
  created_at   timestamptz not null default now()
);

-- ---------- rights_pages: the Know Your Rights library ---------------------
create table if not exists public.rights_pages (
  id          bigint generated by default as identity primary key,
  slug        text not null unique,      -- used in the URL: /rights/:slug
  category    text not null,             -- e.g. 'Pay', 'Rest & time off'
  title       text not null,
  summary     text not null,             -- one-line preview shown on the list
  body        text not null,             -- plain text; '-' or '•' start a bullet line
  updated_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Row Level Security: the helplines and rights content are public reference
-- info, so anyone (anon + authenticated) can read them. Nothing is writable
-- from the client — content is managed here, in SQL.
-- ---------------------------------------------------------------------------
alter table public.contacts     enable row level security;
alter table public.rights_pages enable row level security;

drop policy if exists "contacts are public"     on public.contacts;
drop policy if exists "rights are public"       on public.rights_pages;
create policy "contacts are public" on public.contacts
  for select using (true);
create policy "rights are public" on public.rights_pages
  for select using (true);

-- Seed: helplines
-- Emergency / MOM / TADM numbers are verified against public sources. The
-- embassy and HOME/TWC2 entries are SAMPLE data — verify each on the mission
-- or organisation's official site before launching for real.

delete from public.contacts;
insert into public.contacts (name, category, phone, description, place_id, sort_order) values
  -- Emergency
  ('Police (Emergency)',                   'emergency', '999',           'For crimes, danger to life, or anything happening right now.', null, 1),
  ('Ambulance & Fire (SCDF)',              'emergency', '995',           'Medical emergencies, fires and rescue.', null, 2),
  ('Police Non-Emergency',                 'emergency', '1800 255 0000', 'Report non-urgent matters to the police.', null, 3),
  -- Work & pay
  ('Ministry of Manpower (MOM)',           'work',      '6438 5122',     'Work pass, salary and employment-condition questions.', null, 1),
  ('TADM — Salary & Claims',               'work',      '1800 336 4056', 'Free help with salary and statutory claims (Tripartite Alliance for Dispute Management).', null, 2),
  -- Embassies (home-country missions in Singapore)
  ('Philippines Embassy',                  'embassies', '6737 3977',     'Consular help for Filipino citizens in Singapore.', null, 1),
  ('Embassy of the Republic of Indonesia', 'embassies', '6737 7422',     'Consular help for Indonesian citizens in Singapore.', null, 2),
  ('High Commission of India',             'embassies', '6737 6777',     'Consular help for Indian citizens in Singapore.', null, 3),
  ('Embassy of Myanmar',                   'embassies', '6737 9760',     'Consular help for Myanmar citizens in Singapore.', null, 4),
  ('High Commission of Sri Lanka',         'embassies', '6258 4180',     'Consular help for Sri Lankan citizens in Singapore.', null, 5),
  -- Wellbeing
  ('Samaritans of Singapore',              'wellbeing', '1767',          'Confidential emotional support, 24 hours a day.', null, 1),
  ('HOME (Migrant Workers)',               'wellbeing', '1800 797 7977', 'Shelter, advice and casework for migrant workers in distress. (sample)', null, 2),
  ('TWC2 — Cuff Road Food Programme',      'wellbeing', '6476 9527',     'Support and meals for migrant workers in difficulty. (sample)', null, 3);

-- Seed: rights library
-- Content reflects Ministry of Manpower (MOM) rules for migrant / foreign
-- domestic workers (MDWs / FDWs) in Singapore. Kept short and plain on
-- purpose — a starting point for helpers, not formal legal advice.
-- Bodies use $txt$ quoting so apostrophes don't need escaping.

delete from public.rights_pages;
insert into public.rights_pages (slug, category, title, summary, body) values
(
  'rest-days', 'Rest & time off', 'Rest days',
  'You are entitled to at least one rest day every week.',
  $txt$You must get at least one rest day every week. The day is agreed between you and your employer, and can be taken as one whole day or split into two half-days.

Since 1 January 2023, at least one rest day each month must be taken off — your employer cannot pay you to give it up.

For the other rest days, you can agree to work and be paid extra (compensation in lieu), but only if you consent. Your employer cannot force you to work on a rest day.

A note on what "rest" means: there is no rule that a rest day must be a full 24 hours, so agree clearly with your employer when your rest day starts and ends.

If your rest days are being denied, keep your own record of your working hours and contact the Ministry of Manpower.$txt$
),
(
  'salary-and-deductions', 'Pay', 'Salary & deductions',
  'Your salary must be paid in full and on time.',
  $txt$Your employer must pay your salary in full at least once a month, within 7 days after the end of each salary period, and keep a record of every payment.

Your employer cannot deduct money for things like:
- The foreign worker levy — this is the employer's cost, never yours.
- Placement, recruitment or agency fees.
- Food, lodging or "expenses" beyond what the law and your contract allow.
- Breakages, damages or mistakes.
- As a punishment, or to recover a loan.

You must never be paid less than the monthly salary in your contract. Keep your own record of every payment — the app's "My pay" page is built for exactly this. If something is wrong, you can file a salary claim with TADM.$txt$
),
(
  'employment-contract', 'Your contract', 'Your employment contract',
  'Your agreed terms are written in a Standard Employment Contract.',
  $txt$Foreign domestic workers in Singapore work under a Standard Employment Contract (SEC). It records the terms both you and your employer agreed to.

Your contract should clearly state:
- Your monthly salary.
- Your rest day arrangement.
- Your duties and working hours.
- Your medical care and other benefits.
- How and when your salary is paid.

Both you and your employer should have a signed copy. If you are not sure what is in yours, ask your employer or your employment agency to go through it with you.$txt$
),
(
  'medical-care', 'Health & safety', 'Medical care',
  'Your employer must pay for your medical treatment.',
  $txt$While you are employed, your employer is responsible for your medical care.

The important parts:
- Your employer must bear the full cost of your medical treatment.
- This includes outpatient care and, if needed, hospital care.
- You should never be asked to pay for the treatment of a work injury or illness.
- Your employer must also keep medical insurance for you.

If you feel unwell, tell your employer early and get treated. In a medical emergency, call 995.$txt$
),
(
  'your-documents', 'Your documents', 'Your passport & work permit',
  'Your employer should not keep your passport or work permit.',
  $txt$Your passport and work permit belong to you. Ministry of Manpower rules say your employer should not keep them, and should not force you to hand them over.

What this means in practice:
- You should keep your own passport and work permit.
- If your employer is holding them, they must return them when you ask.
- Keeping a worker's documents is a recognised form of abuse.

If your employer refuses to return your passport or work permit, you can report it to MOM at mom.gov.sg/feedback-fdw, or get help from your embassy or a migrant-worker organisation.$txt$
),
(
  'wellbeing-and-safety', 'Health & safety', 'Well-being & safety at home',
  'You have the right to adequate rest, food and a safe place to stay.',
  $txt$Employers must take care of your well-being, not just your work. This includes giving you adequate rest, proper food, and a safe place to live.

A few things that matter:
- Enough daily rest — not only your weekly rest day.
- Proper meals, or a food allowance if that is what was agreed.
- A safe living space, with proper sleeping arrangements (not a storeroom or unsafe area).
- Personal safety — no physical, verbal or emotional abuse.

When you first arrive in Singapore, you will attend the Settling-In Programme (SIP), which explains your rights and where to get help.

If you ever feel unsafe, call 999 in an emergency, or reach out to one of the helplines listed in this app.$txt$
),
(
  'changing-employer', 'Changing jobs', 'Changing employer',
  'You can change employer, but there are rules to follow.',
  $txt$You are allowed to change employer, but a transfer usually needs your current employer's consent.

What to know:
- A transfer normally needs your employer's agreement.
- Direct employer-to-employer transfers are possible, with or without an agency.
- You should not be made to pay to arrange a transfer.
- Keep working and following your contract until the transfer is approved.

If you want to transfer and your employer refuses, you can contact the Ministry of Manpower or a migrant-worker organisation for help.$txt$
),
(
  'going-home', 'Going home', 'Going home (repatriation)',
  'Your employer must pay for your ticket home.',
  $txt$When your employment ends, your employer must bear the full cost of sending you home — including your airfare and related travel. This applies even if the contract ends early.

What to know:
- Repatriation costs are the employer's responsibility, not yours.
- Before you leave, all outstanding salary must be paid.
- Your employer should not hold back your pay to cover your flight.
- Make sure you leave with your passport and a valid ticket.

If you are being pressured to pay your own way home, contact the Ministry of Manpower or your embassy.$txt$
);
